### ISSUE TITLE
How could train my own data with this work?

### ISSUE THREAD

**Issue by Chen65010445** [liuquande/SRC-MT#2]
You really had done a great work. I want to use it to train my own data which only have two kinds. How could I gain the .csv file? Or is there any regular format to prepare the dataset?

**Comment by liuquande** [comment]
There is a official groundtruth file called "ISIC2018_Task3_Training_GroundTruth.csv" in the training data of Task 3 in ISIC 2018.
You can follow the format of that file to prepare your own dataset.
